version: "3.7"

services:
  app:
    build:
      context: docker
      args:
        TAG: ${BITSONG_TAG}
    user: ${DC_MAP_UID}:1000
    volumes:
    - ./data:/home/bitsong/.bitsongd:rw
    env_file:
      - .env