version: "3.7"

services:
  app:
    build:
      context: docker
      args:
        TAG: ${BITSONG_TAG}
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    volumes:
    - ./data:/home/bitsong/.bitsongd:rw
    env_file:
      - .env