version: "3.7"

services:
  validator:
    build:
      context: docker
      args:
        TAG: ${BITSONG_TAG}
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    restart: unless-stopped
    volumes:
    - ./data:/home/bitsong/.bitsongd:rw
    - .t/mp:/home/bitsong/.bitsongcli:tw
    env_file:
      - .env
  revard:
